import { PropFirmOffer } from "./types";

export const PROPFLOW_MASTER_OFFERS: PropFirmOffer[] = [
  {
    id: "prop_fundedsquad",
    name: "FundedSquad Prop Firm",
    category: "Prop Trading",
    slug: "fundedsquad",
    rating: 4.9,
    reviewCount: 940,
    promoCode: "CHARGE",
    discountSummary: "35% OFF Instant Funding + Buy 1 Get 2 FREE on $25k+",
    payoutModel: "Up to 30% Lifetime RevShare",
    targetUrl: "https://fundedsquad.com/?campaign=thesmartmag&squad=3552",
    profitSplit: "Up to 90% Profit Split",
    maxFunding: "$300,000 (Scalable to $1,500,000)",
    minTradingDays: "0 Days (Instant & Rapid Pass)",
    dailyDrawdown: "4% - 5% Daily Drawdown",
    maxDrawdown: "8% - 10% Total Drawdown",
    leverage: "1:100",
    platforms: ["Match-Trader", "cTrader", "TradeLocker"],
    features: [
      "Exclusive Promo Code 'CHARGE' for 35% Instant Discount",
      "Special 'Buy 1, Get 2 Free' on all $25k+ Evaluation Accounts",
      "Instant Funding Models with Zero Evaluation Phase",
      "Competitive 90% Profit Split with Rapid Payout Timelines",
      "Full Support for EA Trading, Algo Bots & News Scalping",
    ],
    pros: [
      "Unmatched Buy 1 Get 2 Free bundle on $25k+ accounts gives 3x trading accounts",
      "35% instant discount with code 'CHARGE' on instant & evaluation models",
      "Direct instant funding option bypasses challenge phases entirely",
      "High leverage (1:100) and low spreads on crypto and forex pairs",
    ],
    cons: [
      "Buy 1 Get 2 Free deal is a limited-time promotional window",
    ],
    startingPriceUSD: 35,
    highlightBadge: "🔥 BUY 1 GET 2 FREE + 35% OFF",
  },
  {
    id: "prop_equity_edge",
    name: "Equity Edge Prop Firm",
    category: "Prop Trading",
    slug: "equity-edge",
    rating: 4.8,
    reviewCount: 1120,
    promoCode: "THESMARTMAG",
    discountSummary: "Exclusive Partner Access + Fast Payouts & 90% Profit Split",
    payoutModel: "30% Commission / RevShare",
    targetUrl: "https://app.equityedge.io/signup/THESMARTMAG/",
    profitSplit: "85% - 90% Profit Split",
    maxFunding: "$400,000 (Scalable to $2,000,000)",
    minTradingDays: "0 Days (No Minimum Trading Time)",
    dailyDrawdown: "4% - 5% Daily Drawdown",
    maxDrawdown: "8% - 10% Max Drawdown",
    leverage: "1:100",
    platforms: ["cTrader", "Match-Trader", "TradeLocker", "DXTrade"],
    features: [
      "Partner Access via Signup Code: THESMARTMAG",
      "Zero Time Limits & No Minimum Trading Days Requirement",
      "Bi-Weekly Payouts with 85%-90% Profit Split",
      "Refundable Challenge Fees on First Successful Payout",
      "Full EA & Automated Algorithmic Strategy Support",
    ],
    pros: [
      "Clean onboarding and rapid dashboard setup via partner portal",
      "No time limit on challenge phases removes psychological pressure",
      "High profit splits up to 90% and fast withdrawal processing",
      "Transparent rules with zero hidden drawdown tricks",
    ],
    cons: [
      "Weekend crypto leverage requires standard risk buffer",
    ],
    startingPriceUSD: 49,
    highlightBadge: "PARTNER VERIFIED — CODE THESMARTMAG",
  },
  {
    id: "prop_ftm",
    name: "Funded Trader Markets (FTM)",
    category: "Prop Trading",
    slug: "funded-trader-markets",
    rating: 4.8,
    reviewCount: 1420,
    promoCode: "arnab",
    discountSummary: "10% Instant Discount on All Evaluation Challenges",
    payoutModel: "10% Lifetime RevShare on Purchases",
    targetUrl: "https://fundedtradermarkets.com/ref/arnab",
    profitSplit: "Up to 90% Profit Split",
    maxFunding: "$200,000 (Scalable to $2,000,000)",
    minTradingDays: "0 Days (No Minimum Trading Time)",
    dailyDrawdown: "5% Max Daily Drawdown",
    maxDrawdown: "10% Max Total Drawdown",
    leverage: "1:100",
    platforms: ["cTrader", "Match-Trader", "DXTrade"],
    features: [
      "Zero Time Limit on Challenge Phases",
      "Bi-Weekly & On-Demand Payouts",
      "News Trading & Weekend Holding Allowed",
      "Raw Spreads with 0 Markup",
      "Refundable Challenge Fee on First Payout",
    ],
    pros: [
      "No time limit removes psychological rush",
      "Fast payout cycle within 24-48 hours",
      "Direct code 'arnab' applies instant 10% checkout discount",
      "Transparent scaling program up to $2,000,000",
    ],
    cons: [
      "Crypto trading leverage is restricted over high volatility weekends",
      "Requires KYC verification prior to funded stage withdrawal",
    ],
    startingPriceUSD: 85,
    highlightBadge: "EDITOR'S CHOICE - 10% OFF",
  },
  {
    id: "prop_blue_guardian",
    name: "Blue Guardian Prop Firm",
    category: "Prop Trading",
    slug: "blue-guardian",
    rating: 4.8,
    reviewCount: 1890,
    promoCode: "1tgf",
    discountSummary: "New Reserve Pricing: 25K from $48 + 5X Bundles from $41/acct",
    payoutModel: "Up to 15% Lifetime RevShare + Bi-Weekly Payouts",
    targetUrl: "https://blueguardian.com/?afmc=1tgf",
    profitSplit: "85% - 90% Profit Split",
    maxFunding: "$400,000 (Scalable to $2,000,000)",
    minTradingDays: "0 Days (2-Day / 3-Day Pass Available)",
    dailyDrawdown: "4% - 5% (or Optional No Daily Loss Limit)",
    maxDrawdown: "8% - 10% Trailing / Static",
    leverage: "1:100",
    platforms: ["Match-Trader", "cTrader", "TradeLocker", "DXTrade"],
    features: [
      "Updated Reserve Plans: 25K ($48), 50K ($75), 100K ($111), 150K ($222)",
      "5X Bundle Discounts (from $41/account)",
      "Optional No Daily Loss Limit Customization",
      "40% or 50% Consistency Rules Options",
      "Guardian Protector Built-in Risk Shield",
      "Nano Momentum Evaluation & Rapid Payout Schedule",
    ],
    pros: [
      "New lower Reserve challenge fees starting at just $48",
      "Customizable evaluation rules: No Daily Loss Limit, 2/3-day pass",
      "5X Bundles give significant per-account discounts for multi-account scaling",
      "Guardian Protector automated stop-loss protection prevents accidental breach",
    ],
    cons: [
      "Add-on customizations (like No Daily Loss) slightly increase checkout cost",
    ],
    startingPriceUSD: 48,
    highlightBadge: "NEW RESERVE PRICING — FROM $48",
  },
  {
    id: "prop_atlas_funded",
    name: "Atlas Funded",
    category: "Prop Trading",
    slug: "atlas-funded",
    rating: 4.9,
    reviewCount: 980,
    promoCode: "12275",
    discountSummary: "20% Instant Discount + $5 Free Challenge Passes (FTPs)",
    payoutModel: "20% on Purchases + $5 Access Challenge FTPs",
    targetUrl: "https://affiliates.atlasfunded.com/Tracking/click/?affid=12275&campaign=11320&product_id=1&t_type=Register&t_lang=EN",
    profitSplit: "85% - 90% Profit Share",
    maxFunding: "$300,000",
    minTradingDays: "1 Day Minimum",
    dailyDrawdown: "4% - 5% Trailing / Static",
    maxDrawdown: "8% - 10% Total Drawdown",
    leverage: "1:50",
    platforms: ["TradeLocker", "cTrader"],
    features: [
      "20% Off with Exclusive Partner Code: 12275",
      "Instant Free Challenge Pass Tokens ($5 FTPs)",
      "Instant Scaling Tiers for Profitable Traders",
      "Low Commission & Zero Swap Options",
    ],
    pros: [
      "One of the highest discounts (20% flat with code 12275)",
      "High leverage and instant execution on TradeLocker",
      "Active Discord community with direct support",
    ],
    cons: [
      "Strict consistency rule on aggressive high-lot news gambles",
    ],
    startingPriceUSD: 70,
    highlightBadge: "20% OFF + $5 FTPs",
  },
  {
    id: "prop_aquafunded",
    name: "AquaFunded",
    category: "Prop Trading",
    slug: "aquafunded",
    rating: 4.7,
    reviewCount: 1650,
    promoCode: "6e9",
    discountSummary: "Up to 20% Challenge Rebate + 90% Profit Split",
    payoutModel: "Up to 20% Commission on Purchases",
    targetUrl: "https://www.aquafunded.com/?afmc=6e9",
    profitSplit: "Up to 90% Payouts",
    maxFunding: "$400,000",
    minTradingDays: "0 Days",
    dailyDrawdown: "5% Max Daily Drawdown",
    maxDrawdown: "10% Max Total Drawdown",
    leverage: "1:100",
    platforms: ["cTrader", "Match-Trader", "DXTrade"],
    features: [
      "1-Step, 2-Step, and Instant Funding Programs",
      "Fastest 14-day Initial Payout Cycle",
      "Automated Trade Copier Allowed",
      "Crypto, Forex, Indices, and Metals Supported",
    ],
    pros: [
      "1-Step rapid evaluation option available",
      "90% profit split guarantee on passed accounts",
      "Code '6e9' applies highest partner tier pricing",
    ],
    cons: [
      "Instant funding accounts have lower initial profit split (70%)",
    ],
    startingPriceUSD: 65,
    highlightBadge: "UP TO 20% REBATE",
  },
  {
    id: "prop_pocket_option",
    name: "Pocket Option Trading Terminal",
    category: "Trading & Binary",
    slug: "pocket-option",
    rating: 4.8,
    reviewCount: 3400,
    promoCode: "50START",
    discountSummary: "50% Instant Deposit Match Bonus + Free $10,000 Demo",
    payoutModel: "50% Bonus + Up to 80% RevShare / $50 CPA",
    targetUrl: "https://v4.lands-po.com/en/land/001-QT-02?utm_campaign=865170&utm_source=affiliate&utm_medium=sr&a=5zrdNdJrvFxqJO&al=1794767&ac=smart-link&cid=979105&code=50START",
    profitSplit: "Up to 96% Payout per Trade",
    maxFunding: "$50,000 Balance",
    minTradingDays: "Instant 24/7 Access",
    dailyDrawdown: "No Limits",
    maxDrawdown: "No Limits",
    leverage: "1:1000",
    platforms: ["Web App", "iOS", "Android", "Telegram Bot"],
    features: [
      "Instant 50% Deposit Match with code: 50START",
      "Free $10,000 Refillable Practice Terminal",
      "Copy Trading / Social Trader Leaderboard",
      "Fast Crypto & UPI Deposits/Withdrawals",
    ],
    pros: [
      "Instant account access with $5 minimum deposit",
      "Zero fees on crypto withdrawals",
      "Social copy trading lets beginners mirror verified pros",
    ],
    cons: [
      "High frequency binary options require strict risk management",
    ],
    startingPriceUSD: 5,
    highlightBadge: "50% DEPOSIT BONUS",
  },
];
