import { PropFirmOffer } from "./types";

export const PROPFLOW_MASTER_OFFERS: PropFirmOffer[] = [
  {
    id: "prop_ftm",
    name: "Funded Trader Markets (FTM)",
    category: "Prop Trading",
    slug: "funded-trader-markets",
    rating: 4.8,
    reviewCount: 1420,
    promoCode: "arnab",
    discountSummary: "10% Instant Discount on All Evaluation Challenges",
    payoutModel: "10% Lifetime RevShare on Purchases",
    targetUrl: "https://fundedtradermarkets.com/ref/arnab",
    profitSplit: "Up to 90% Profit Split",
    maxFunding: "$200,000 (Scalable to $2,000,000)",
    minTradingDays: "0 Days (No Minimum Trading Time)",
    dailyDrawdown: "5% Max Daily Drawdown",
    maxDrawdown: "10% Max Total Drawdown",
    leverage: "1:100",
    platforms: ["cTrader", "Match-Trader", "DXTrade"],
    features: [
      "Zero Time Limit on Challenge Phases",
      "Bi-Weekly & On-Demand Payouts",
      "News Trading & Weekend Holding Allowed",
      "Raw Spreads with 0 Markup",
      "Refundable Challenge Fee on First Payout",
    ],
    pros: [
      "No time limit removes psychological rush",
      "Fast payout cycle within 24-48 hours",
      "Direct code 'arnab' applies instant 10% checkout discount",
      "Transparent scaling program up to $2,000,000",
    ],
    cons: [
      "Crypto trading leverage is restricted over high volatility weekends",
      "Requires KYC verification prior to funded stage withdrawal",
    ],
    startingPriceUSD: 85,
    highlightBadge: "EDITOR'S CHOICE - 10% OFF",
  },
  {
    id: "prop_atlas_funded",
    name: "Atlas Funded",
    category: "Prop Trading",
    slug: "atlas-funded",
    rating: 4.9,
    reviewCount: 980,
    promoCode: "12275",
    discountSummary: "20% Instant Discount + $5 Free Challenge Passes (FTPs)",
    payoutModel: "20% on Purchases + $5 Access Challenge FTPs",
    targetUrl: "https://affiliates.atlasfunded.com/Tracking/click/?affid=12275&campaign=11320&product_id=1&t_type=Register&t_lang=EN",
    profitSplit: "85% - 90% Profit Share",
    maxFunding: "$300,000",
    minTradingDays: "1 Day Minimum",
    dailyDrawdown: "4% - 5% Trailing / Static",
    maxDrawdown: "8% - 10% Total Drawdown",
    leverage: "1:50",
    platforms: ["TradeLocker", "cTrader"],
    features: [
      "20% Off with Exclusive Partner Code: 12275",
      "Instant Free Challenge Pass Tokens ($5 FTPs)",
      "Instant Scaling Tiers for Profitable Traders",
      "Low Commission & Zero Swap Options",
    ],
    pros: [
      "One of the highest discounts (20% flat with code 12275)",
      "High leverage and instant execution on TradeLocker",
      "Active Discord community with direct support",
    ],
    cons: [
      "Strict consistency rule on aggressive high-lot news gambles",
    ],
    startingPriceUSD: 70,
    highlightBadge: "20% OFF + $5 FTPs",
  },
  {
    id: "prop_aquafunded",
    name: "AquaFunded",
    category: "Prop Trading",
    slug: "aquafunded",
    rating: 4.7,
    reviewCount: 1650,
    promoCode: "6e9",
    discountSummary: "Up to 20% Challenge Rebate + 90% Profit Split",
    payoutModel: "Up to 20% Commission on Purchases",
    targetUrl: "https://www.aquafunded.com/?afmc=6e9",
    profitSplit: "Up to 90% Payouts",
    maxFunding: "$400,000",
    minTradingDays: "0 Days",
    dailyDrawdown: "5% Max Daily Drawdown",
    maxDrawdown: "10% Max Total Drawdown",
    leverage: "1:100",
    platforms: ["cTrader", "Match-Trader", "DXTrade"],
    features: [
      "1-Step, 2-Step, and Instant Funding Programs",
      "Fastest 14-day Initial Payout Cycle",
      "Automated Trade Copier Allowed",
      "Crypto, Forex, Indices, and Metals Supported",
    ],
    pros: [
      "1-Step rapid evaluation option available",
      "90% profit split guarantee on passed accounts",
      "Code '6e9' applies highest partner tier pricing",
    ],
    cons: [
      "Instant funding accounts have lower initial profit split (70%)",
    ],
    startingPriceUSD: 65,
    highlightBadge: "UP TO 20% REBATE",
  },
  {
    id: "prop_pocket_option",
    name: "Pocket Option Trading Terminal",
    category: "Trading & Binary",
    slug: "pocket-option",
    rating: 4.8,
    reviewCount: 3400,
    promoCode: "50START",
    discountSummary: "50% Instant Deposit Match Bonus + Free $10,000 Demo",
    payoutModel: "50% Bonus + Up to 80% RevShare / $50 CPA",
    targetUrl: "https://v4.lands-po.com/en/land/001-QT-02?utm_campaign=865170&utm_source=affiliate&utm_medium=sr&a=5zrdNdJrvFxqJO&al=1794767&ac=smart-link&cid=979105&code=50START",
    profitSplit: "Up to 96% Payout per Trade",
    maxFunding: "$50,000 Balance",
    minTradingDays: "Instant 24/7 Access",
    dailyDrawdown: "No Limits",
    maxDrawdown: "No Limits",
    leverage: "1:1000",
    platforms: ["Web App", "iOS", "Android", "Telegram Bot"],
    features: [
      "Instant 50% Deposit Match with code: 50START",
      "Free $10,000 Refillable Practice Terminal",
      "Copy Trading / Social Trader Leaderboard",
      "Fast Crypto & UPI Deposits/Withdrawals",
    ],
    pros: [
      "Instant account access with $5 minimum deposit",
      "Zero fees on crypto withdrawals",
      "Social copy trading lets beginners mirror verified pros",
    ],
    cons: [
      "High frequency binary options require strict risk management",
    ],
    startingPriceUSD: 5,
    highlightBadge: "50% DEPOSIT BONUS",
  },
];
